BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "frankData" (
	"id"	INTEGER NOT NULL UNIQUE,
	"tweetNumber"	INTEGER,
	"lastTweetTimestamp"	INTEGER,
	"tweetToReplyId"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
